// ui/src/pages/resume/index.tsx
import RightArrow from '../../components/atoms/RightArrow'
import { ReactComponent as Github } from '../../assets/github.svg'
import { ReactComponent as Twitter } from '../../assets/twitter.svg'
import { ReactComponent as LinkedIn } from '../../assets/linkedin.svg'
import { ReactComponent as Hammer } from '../../assets/hammer.svg'

import styles from './index.module.css'

export default () =>
  <div className={styles.resume}>
    <div>
      <p className="-ml-5">resume</p>
      <div className={styles.links}>
        <div className="flex flex-row pb-3">
          <span>links</span>
          <a href="https://github.com/taybart" target="_blank" className="pl-3">
            <RightArrow />
            <Github width="15" className="inline fill-white" />
            github
          </a>
          <a href="https://twitter.com/taybart_" target="_blank" className="pl-3">
            <RightArrow />
            <Twitter width="15" className="inline fill-white" />
            twitter
          </a>
          <a
            href="https://linkedin.com/in/taylor-bartlett-3542609a"
            target="_blank"
            className="pl-3"
          >
            <RightArrow />
            <LinkedIn width="15" className="inline fill-white" />
            linkedin
          </a>
          <a href="mailto:taybart@gmail.com" target="_blank" className="pl-3">
            <RightArrow />
            <Hammer width="15" className="inline fill-white" />
            need something built?
          </a>
        </div>
      </div>
      <div className={styles['job-description']}>
        <a target="blank" href="https://journeyid.com">@journey</a>
        <div className={styles.description}>
          Journey is bringing trust, identity and zero-knowledge privacy to the
          contact center & beyond
        </div>
        <div className={styles.job}>
          2021-now <RightArrow /> <b>director of engineering</b>
        </div>
        <div className={styles.job}>
          2020-2021 <RightArrow />
          <b>principal engineer & developement manager</b>
        </div>
        <div className={styles.job}>
          <RightArrow /> 2018-2020 <b>lead software engineer</b>
        </div>
      </div>
      <div className={styles['job-description']}>
        <p>@the spiga group</p>
        <div className={styles.description}>Real time crypto index fund</div>
        <div className={styles.job}>
          2017-2018 <RightArrow /> <b>lead software engineer</b>
        </div>
      </div>
      <div className={styles['job-description']}>
        <p>@mfactor engineering</p>
        <div className={styles.description}>factory optimization</div>
        <div className={styles.job}>
          2014-2017 <RightArrow /> <b>co-founder</b>
        </div>
      </div>
      <div className={styles['job-description']}>
        <p>@university of colorado, boulder</p>
        <div className={styles.job}>
          2011-2015 <RightArrow /> bs, electrical and computer engineering
        </div>
      </div>
    </div>
  </div>

// ui/src/routes/Resume.svelte
<script lang="ts">
  import RightArrow from '../components/atoms/RightArrow.svelte'
  import Github from '../assets/github.svg'
  import Twitter from '../assets/twitter.svg'
  import LinkedIn from '../assets/linkedin.svg'
</script>

<div class="resume">
  <div>
    <p class="font-thin">my journey so far</p>
    <div>
      <div class="job">
        <RightArrow /> 2020-now <b>principal engineer & developement manager</b>
        journey
      </div>
      <div class="job">
        <RightArrow /> 2018-2020 <b>lead software engineer</b> journey
        <div class="description">
          Journey is bringing trust, identity and zero-knowledge privacy to the
          contact center & beyond
        </div>
      </div>
    </div>
    <div class="job">
      <RightArrow /> 2017-2018 <b>lead software engineer</b> the spiga group [real
      time index fund]
    </div>
    <div class="job">
      <RightArrow /> 2014-2017 <b>co-founder</b> mfactor engineering [factory optimization]
    </div>
    <div class="job">
      <RightArrow /> 2015 <b>bs</b> electrical and computer engineering, university
      of colorado
    </div>
  </div>
  <div class="links absolute bottom-8 left-8">
    <span>links</span>
    <div class="flex flex-row">
      <a href="https://github.com/taybart" target="_blank" class="pl-3">
        <RightArrow />
        <Github width="15" class="inline fill-white" />
        github
      </a>
      <a href="https://twitter.com/taybart_" target="_blank" class="pl-3">
        <RightArrow />
        <Twitter width="15" class="inline fill-white" />
        twitter
      </a>
      <a
        href="https://linkedin.com/in/taylor-bartlett-3542609a"
        target="_blank"
        class="pl-3"
      >
        <RightArrow />
        <LinkedIn width="15" class="inline fill-white" />
        linkedin
      </a>
      <a href="https://example.com" target="_blank" class="pl-3">
        <RightArrow />
        <LinkedIn width="15" class="inline fill-white" />
        Want your dream app?
      </a>
    </div>
  </div>
</div>

<style lang="postcss">
  .resume {
    @apply mx-1 flex h-full flex-col items-start pt-20 md:mx-32;
  }

  .job {
    @apply pl-3 font-extralight;
  }
  .job .description {
    @apply pl-6 text-sm;
  }
</style>
